const express = require('express');
const router = express.Router();

// All prices in INR (₹) per month
const properties = [
  {
    id: '1',
    title: 'Antilia-Style Sky Villa',
    description: 'Breathtaking panoramic views from this ultra-luxury penthouse in the heart of Mumbai. Floor-to-ceiling windows, private rooftop terrace with infinity pool, dedicated elevator, and world-class concierge. The pinnacle of Mumbai luxury living.',
    price: 850000,
    priceUnit: 'month',
    type: 'Penthouse',
    bedrooms: 4,
    bathrooms: 4,
    area: 5800,
    location: { address: 'Altamount Road, Cumballa Hill', city: 'Mumbai', state: 'Maharashtra', zip: '400026', lat: 18.9700, lng: 72.8079 },
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
    ],
    amenities: ['Rooftop Infinity Pool', 'Concierge', 'Valet Parking', 'Home Gym', 'Smart Home', 'Generator Backup'],
    featured: true, rating: 4.9, reviews: 47, available: true,
    tags: ['Ultra Luxury', 'Sea View', 'New'],
  },
  {
    id: '2',
    title: 'DLF Camellias Penthouse',
    description: 'Exclusive penthouse in Gurugram\'s most prestigious address — DLF Camellias. Sprawling interiors with Italian marble flooring, imported kitchen, private terrace garden, and butler service. Redefining luxury in NCR.',
    price: 700000,
    priceUnit: 'month',
    type: 'Penthouse',
    bedrooms: 5,
    bathrooms: 5,
    area: 7200,
    location: { address: 'DLF Camellias, Golf Course Road', city: 'Gurugram', state: 'Haryana', zip: '122009', lat: 28.4595, lng: 77.0266 },
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
    ],
    amenities: ['Butler Service', 'Private Elevator', 'Golf Course View', 'Home Theater', 'Pool', '24/7 Security'],
    featured: true, rating: 5.0, reviews: 12, available: true,
    tags: ['Ultra Luxury', 'Golf View', 'Exclusive'],
  },
  {
    id: '3',
    title: 'Bandra Sea-Facing Villa',
    description: 'Stunning 3BHK sea-facing apartment in Bandra West with panoramic Arabian Sea views. Modern open kitchen, large balconies, and premium amenities in a quiet lane steps from Bandstand promenade.',
    price: 320000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    location: { address: 'Carter Road, Bandra West', city: 'Mumbai', state: 'Maharashtra', zip: '400050', lat: 19.0607, lng: 72.8362 },
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    amenities: ['Sea View', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Terrace'],
    featured: true, rating: 4.8, reviews: 83, available: true,
    tags: ['Sea View', 'Hot', 'Bandra'],
  },
  {
    id: '4',
    title: 'Indiranagar Modern Loft',
    description: 'Chic industrial-style loft in Bengaluru\'s trendiest neighbourhood. Exposed brick, 14-foot ceilings, chef\'s kitchen with quartz countertops, and a private rooftop perfect for entertaining.',
    price: 95000,
    priceUnit: 'month',
    type: 'Loft',
    bedrooms: 2,
    bathrooms: 2,
    area: 1900,
    location: { address: '100 Feet Road, Indiranagar', city: 'Bengaluru', state: 'Karnataka', zip: '560038', lat: 12.9716, lng: 77.6412 },
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800',
    ],
    amenities: ['High Ceilings', 'Chef Kitchen', 'Rooftop Terrace', 'Pet Friendly', 'Bike Storage', 'EV Charging'],
    featured: true, rating: 4.7, reviews: 62, available: true,
    tags: ['Artisan', 'Trendy', 'Hot'],
  },
  {
    id: '5',
    title: 'Koramangala Studio Apartment',
    description: 'Beautifully designed studio apartment in Bengaluru\'s startup hub. Fully furnished with modular kitchen, smart TV, high-speed fiber internet, and access to co-working space in building.',
    price: 28000,
    priceUnit: 'month',
    type: 'Studio',
    bedrooms: 0,
    bathrooms: 1,
    area: 650,
    location: { address: '5th Block, Koramangala', city: 'Bengaluru', state: 'Karnataka', zip: '560095', lat: 12.9352, lng: 77.6245 },
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800',
    ],
    amenities: ['Fully Furnished', 'WiFi', 'Co-working Space', 'Gym', 'Laundry', 'Power Backup'],
    featured: false, rating: 4.5, reviews: 134, available: true,
    tags: ['Affordable', 'Fully Furnished', 'Popular'],
  },
  {
    id: '6',
    title: 'Lutyens Delhi Bungalow',
    description: 'Grand colonial bungalow in the prestigious Lutyens Delhi zone. Set on a 1-acre plot with manicured gardens, staff quarters, 7 bedrooms, and heritage architecture meticulously restored.',
    price: 1200000,
    priceUnit: 'month',
    type: 'Villa',
    bedrooms: 7,
    bathrooms: 7,
    area: 12000,
    location: { address: 'Prithviraj Road, Lutyens Zone', city: 'New Delhi', state: 'Delhi', zip: '110011', lat: 28.5951, lng: 77.2088 },
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800',
    ],
    amenities: ['1-Acre Garden', 'Staff Quarters', 'Swimming Pool', 'Library', 'Garage', 'Heritage Architecture'],
    featured: true, rating: 4.95, reviews: 8, available: false,
    tags: ['Heritage', 'Iconic', 'Rare Find'],
  },
  {
    id: '7',
    title: 'Jubilee Hills Luxury Villa',
    description: 'Premium 4BHK villa in Hyderabad\'s most sought-after neighbourhood. Double-height living room, modular kitchen, landscaped garden, private pool, and dedicated home office space.',
    price: 180000,
    priceUnit: 'month',
    type: 'Villa',
    bedrooms: 4,
    bathrooms: 4,
    area: 4500,
    location: { address: 'Road No. 36, Jubilee Hills', city: 'Hyderabad', state: 'Telangana', zip: '500033', lat: 17.4318, lng: 78.4078 },
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
    ],
    amenities: ['Private Pool', 'Landscaped Garden', 'Home Office', 'Gym', 'Smart Home', 'Solar Power'],
    featured: true, rating: 4.85, reviews: 29, available: true,
    tags: ['Villa', 'Private Pool', 'Unique'],
  },
  {
    id: '8',
    title: 'Powai Lake View Apartment',
    description: 'Elegant 3BHK apartment with stunning Powai Lake views. Premium tower in Hiranandani Gardens with European-style architecture, world-class amenities, and serene surroundings.',
    price: 95000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    location: { address: 'Hiranandani Gardens, Powai', city: 'Mumbai', state: 'Maharashtra', zip: '400076', lat: 19.1197, lng: 72.9082 },
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['Lake View', 'Clubhouse', 'Pool', 'Tennis Court', 'Jogging Track', 'Valet'],
    featured: false, rating: 4.6, reviews: 91, available: true,
    tags: ['Lake View', 'Family Friendly'],
  },
  {
    id: '9',
    title: 'Vasant Vihar Duplex',
    description: 'Spacious duplex apartment in South Delhi\'s premium Vasant Vihar colony. Two floors of elegant living with a private garden, imported fittings, and a prime location near diplomatic enclave.',
    price: 250000,
    priceUnit: 'month',
    type: 'Duplex',
    bedrooms: 4,
    bathrooms: 4,
    area: 4800,
    location: { address: 'Vasant Vihar, South Delhi', city: 'New Delhi', state: 'Delhi', zip: '110057', lat: 28.5517, lng: 77.1574 },
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
    ],
    amenities: ['Private Garden', 'Duplex Layout', 'Imported Fittings', '2-Car Garage', 'Staff Room', 'Modular Kitchen'],
    featured: false, rating: 4.7, reviews: 38, available: true,
    tags: ['Duplex', 'South Delhi', 'Spacious'],
  },
  {
    id: '10',
    title: 'Whitefield IT Hub Studio',
    description: 'Smart studio apartment 5 minutes from Whitefield IT park. Fully furnished with modular furniture, fast internet, and access to rooftop garden. Ideal for IT professionals.',
    price: 22000,
    priceUnit: 'month',
    type: 'Studio',
    bedrooms: 0,
    bathrooms: 1,
    area: 580,
    location: { address: 'ITPL Main Road, Whitefield', city: 'Bengaluru', state: 'Karnataka', zip: '560066', lat: 12.9698, lng: 77.7499 },
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    amenities: ['Fully Furnished', '500 Mbps WiFi', 'AC', 'Power Backup', 'Security', 'Rooftop Garden'],
    featured: false, rating: 4.4, reviews: 210, available: true,
    tags: ['Affordable', 'IT Hub', 'Furnished'],
  },
  {
    id: '11',
    title: 'Worli Sea Face Penthouse',
    description: 'Crown jewel of Worli skyline — a massive 5BHK penthouse with 270-degree sea view. Wraparound balcony, private jacuzzi, Italian kitchen, and a dedicated home cinema room.',
    price: 1500000,
    priceUnit: 'month',
    type: 'Penthouse',
    bedrooms: 5,
    bathrooms: 6,
    area: 9500,
    location: { address: 'Worli Sea Face, Worli', city: 'Mumbai', state: 'Maharashtra', zip: '400030', lat: 19.0090, lng: 72.8182 },
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
    ],
    amenities: ['270° Sea View', 'Private Jacuzzi', 'Home Cinema', 'Italian Kitchen', 'Staff Quarters', 'Helipad Access'],
    featured: true, rating: 5.0, reviews: 5, available: true,
    tags: ['Ultra Luxury', 'Sea View', 'Iconic'],
  },
  {
    id: '12',
    title: 'Aundh Wellness Apartment',
    description: 'Thoughtfully designed 2BHK in Pune\'s serene Aundh neighbourhood. Vaastu-compliant layout, natural ventilation, rooftop organic garden, and proximity to top schools and hospitals.',
    price: 35000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    location: { address: 'DP Road, Aundh', city: 'Pune', state: 'Maharashtra', zip: '411007', lat: 18.5580, lng: 73.8087 },
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['Vaastu Compliant', 'Organic Garden', 'Gym', 'Kids Play Area', 'Rainwater Harvesting', 'Solar'],
    featured: false, rating: 4.6, reviews: 77, available: true,
    tags: ['Eco Friendly', 'Family Friendly', 'Pune'],
  },
  {
    id: '13',
    title: 'Connaught Place Premium Office-Home',
    description: 'Rare live-work apartment above Connaught Place\'s iconic circular market. Massive 3BHK with high ceilings, heritage views, and a versatile layout perfect for executives and creative professionals.',
    price: 175000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 2600,
    location: { address: 'Connaught Place, Central Delhi', city: 'New Delhi', state: 'Delhi', zip: '110001', lat: 28.6315, lng: 77.2167 },
    images: [
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    ],
    amenities: ['Heritage View', 'High Ceilings', 'Work-from-Home Setup', 'Concierge', 'Metro Access', 'Parking'],
    featured: false, rating: 4.5, reviews: 43, available: true,
    tags: ['Central Delhi', 'Heritage', 'Executive'],
  },
  {
    id: '14',
    title: 'Alipore Heritage Mansion',
    description: 'Majestic colonial-era mansion in Kolkata\'s most aristocratic neighbourhood. Original Raj-era architecture with contemporary renovations, expansive lawns, 6 bedrooms, and a rich history.',
    price: 280000,
    priceUnit: 'month',
    type: 'Villa',
    bedrooms: 6,
    bathrooms: 6,
    area: 9000,
    location: { address: 'Alipore Road, Alipore', city: 'Kolkata', state: 'West Bengal', zip: '700027', lat: 22.5344, lng: 88.3333 },
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800',
    ],
    amenities: ['Heritage Architecture', 'Lawn', 'Ballroom', 'Library', 'Staff Quarters', 'Garage'],
    featured: true, rating: 4.8, reviews: 19, available: true,
    tags: ['Heritage', 'Colonial', 'Rare Find'],
  },
  {
    id: '15',
    title: 'HSR Layout Smart Home',
    description: 'Ultra-modern 3BHK smart home in Bengaluru\'s HSR Layout. Fully automated lighting, temperature, security, and appliances controllable from your phone. IGBC green certified building.',
    price: 65000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    location: { address: 'Sector 6, HSR Layout', city: 'Bengaluru', state: 'Karnataka', zip: '560102', lat: 12.9116, lng: 77.6474 },
    images: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
    ],
    amenities: ['Full Home Automation', 'EV Charging', 'Solar Power', 'IGBC Green', 'Gym', 'Rooftop Lounge'],
    featured: false, rating: 4.7, reviews: 56, available: true,
    tags: ['Smart Home', 'Green', 'Modern'],
  },
  {
    id: '16',
    title: 'Gachibowli Tech Park Villa',
    description: 'Stunning 4BHK independent villa in Hyderabad\'s HITEC City zone. Private pool, landscaped garden, 3-car garage, home office with fiber internet, and premium club facilities.',
    price: 150000,
    priceUnit: 'month',
    type: 'Villa',
    bedrooms: 4,
    bathrooms: 4,
    area: 5200,
    location: { address: 'Nanakramguda, Gachibowli', city: 'Hyderabad', state: 'Telangana', zip: '500032', lat: 17.4156, lng: 78.3477 },
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
    ],
    amenities: ['Private Pool', '3-Car Garage', 'Home Office', 'Landscaped Garden', 'CCTV', 'Fiber Internet'],
    featured: true, rating: 4.8, reviews: 34, available: true,
    tags: ['Villa', 'HITEC City', 'Pool'],
  },
  {
    id: '17',
    title: 'Marine Drive Sea Breeze',
    description: 'Iconic 2BHK apartment directly on Marine Drive — Mumbai\'s Queen\'s Necklace. Wake up to stunning sea views every morning. Recently renovated with designer interiors and a large wraparound balcony.',
    price: 220000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1600,
    location: { address: 'Marine Drive, Nariman Point', city: 'Mumbai', state: 'Maharashtra', zip: '400020', lat: 18.9388, lng: 72.8238 },
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800',
    ],
    amenities: ['Direct Sea View', 'Wraparound Balcony', 'Designer Interior', 'Doorman', 'Parking', 'Generator'],
    featured: false, rating: 4.9, reviews: 61, available: true,
    tags: ['Sea View', 'Iconic', 'Marine Drive'],
  },
  {
    id: '18',
    title: 'Satellite Road Modern 2BHK',
    description: 'Stylish 2BHK apartment in Ahmedabad\'s upscale Satellite area. Vaastu-friendly layout, modular kitchen, covered parking, and a vibrant neighbourhood with top restaurants and malls nearby.',
    price: 30000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    location: { address: 'Satellite Road, Satellite', city: 'Ahmedabad', state: 'Gujarat', zip: '380015', lat: 23.0225, lng: 72.5714 },
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    amenities: ['Vaastu Friendly', 'Modular Kitchen', 'Covered Parking', 'Gym', 'CCTV', 'Power Backup'],
    featured: false, rating: 4.4, reviews: 88, available: true,
    tags: ['Affordable', 'Vaastu', 'Ahmedabad'],
  },
  {
    id: '19',
    title: 'Besant Nagar Beach House',
    description: 'Gorgeous 3BHK bungalow 2 minutes from Elliot\'s Beach in Chennai. Private garden, open terrace with sea breeze, vintage wooden floors, and a relaxed coastal lifestyle in a premium neighbourhood.',
    price: 85000,
    priceUnit: 'month',
    type: 'Villa',
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    location: { address: 'Besant Nagar, Elliot\'s Beach', city: 'Chennai', state: 'Tamil Nadu', zip: '600090', lat: 13.0002, lng: 80.2718 },
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    amenities: ['Beach Access', 'Private Garden', 'Terrace', 'Vintage Floors', 'Pet Friendly', 'Parking'],
    featured: false, rating: 4.7, reviews: 52, available: true,
    tags: ['Beach', 'Bungalow', 'Chennai'],
  },
  {
    id: '20',
    title: 'Sector 17 Chandigarh Apartment',
    description: '3BHK in Le Corbusier\'s planned city, steps from Sector 17 plaza. Wide boulevards, lush greenery, and a peaceful lifestyle. Ideal for families seeking safety, cleanliness, and urban convenience.',
    price: 45000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    location: { address: 'Sector 17-C, Chandigarh', city: 'Chandigarh', state: 'Punjab', zip: '160017', lat: 30.7403, lng: 76.7783 },
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800',
    ],
    amenities: ['Wide Balcony', 'Park View', 'Covered Parking', 'Lift', 'Power Backup', 'Security'],
    featured: false, rating: 4.5, reviews: 66, available: true,
    tags: ['Family Friendly', 'Planned City', 'Peaceful'],
  },
  {
    id: '21',
    title: 'Salt Lake City IT Township',
    description: 'Contemporary 2BHK in Kolkata\'s premier IT township — Salt Lake Sector V. Fully furnished, walking distance to major IT companies, and modern amenities at an unbeatable price point.',
    price: 25000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 980,
    location: { address: 'Sector V, Salt Lake City', city: 'Kolkata', state: 'West Bengal', zip: '700091', lat: 22.5697, lng: 88.4342 },
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    amenities: ['Fully Furnished', 'WiFi', 'Gym', 'Security', 'Laundry', 'IT Hub Proximity'],
    featured: false, rating: 4.3, reviews: 112, available: true,
    tags: ['IT Hub', 'Furnished', 'Affordable'],
  },
  {
    id: '22',
    title: 'Viman Nagar Premium 3BHK',
    description: 'Upscale 3BHK apartment near Pune airport in the vibrant Viman Nagar area. European-style interiors, large balcony, rooftop infinity pool, and proximity to Phoenix Mall and top restaurants.',
    price: 55000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 3,
    area: 1700,
    location: { address: 'Viman Nagar, Near Airport', city: 'Pune', state: 'Maharashtra', zip: '411014', lat: 18.5679, lng: 73.9143 },
    images: [
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
    ],
    amenities: ['Rooftop Pool', 'Gym', 'Concierge', 'Mall Proximity', 'Balcony', 'CCTV'],
    featured: false, rating: 4.6, reviews: 48, available: true,
    tags: ['Near Airport', 'Modern', 'Pune'],
  },
  {
    id: '23',
    title: 'Adyar Riverside Bungalow',
    description: 'Tranquil 4BHK independent bungalow on the banks of the Adyar river in Chennai. Lush garden, river-facing verandah, traditional Chettinad design elements with modern comforts throughout.',
    price: 120000,
    priceUnit: 'month',
    type: 'Villa',
    bedrooms: 4,
    bathrooms: 4,
    area: 4200,
    location: { address: 'Kasturba Nagar, Adyar', city: 'Chennai', state: 'Tamil Nadu', zip: '600020', lat: 13.0067, lng: 80.2567 },
    images: [
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
    ],
    amenities: ['River View', 'Garden', 'Verandah', 'Traditional Design', 'Parking', 'Generator'],
    featured: false, rating: 4.8, reviews: 27, available: false,
    tags: ['River View', 'Heritage', 'Chennai'],
  },
  {
    id: '24',
    title: 'Frazer Town Garden Apartment',
    description: 'Charming 2BHK in Bengaluru\'s vintage Frazer Town — tree-lined streets, excellent schools nearby, and a strong community vibe. Spacious rooms, wooden floors, and a lovely garden view.',
    price: 42000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    area: 1350,
    location: { address: 'Dispensary Road, Frazer Town', city: 'Bengaluru', state: 'Karnataka', zip: '560005', lat: 12.9791, lng: 77.6085 },
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    amenities: ['Garden View', 'Wooden Floors', 'Parking', 'School Proximity', 'Pet Friendly', 'Storage'],
    featured: false, rating: 4.5, reviews: 73, available: true,
    tags: ['Garden View', 'Family Friendly', 'Vintage'],
  },
  {
    id: '25',
    title: 'Cyber City Gurgaon Highrise',
    description: 'Magnificent 4BHK in a gleaming highrise overlooking Gurugram\'s Cyber City skyline. Wraparound terrace, state-of-the-art gym, infinity pool, and direct metro access — for the ultimate modern executive.',
    price: 350000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    location: { address: 'DLF Phase 2, Cyber City', city: 'Gurugram', state: 'Haryana', zip: '122002', lat: 28.4947, lng: 77.0886 },
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    amenities: ['City Skyline View', 'Wraparound Terrace', 'Infinity Pool', 'Metro Access', 'Concierge', 'EV Parking'],
    featured: true, rating: 4.9, reviews: 41, available: true,
    tags: ['Skyline View', 'Executive', 'Metro'],
  },
  {
    id: '26',
    title: 'Old Goa Portuguese Villa',
    description: 'Extraordinary restored 18th-century Portuguese villa in Old Goa. 5 bedrooms, azulejo tile work, grand courtyard with fountain, private pool, and lush tropical garden. A living piece of Goan heritage.',
    price: 320000,
    priceUnit: 'month',
    type: 'Villa',
    bedrooms: 5,
    bathrooms: 5,
    area: 7500,
    location: { address: 'Old Goa Road, Velha Goa', city: 'Goa', state: 'Goa', zip: '403402', lat: 15.5057, lng: 73.9086 },
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800',
    ],
    amenities: ['Private Pool', 'Courtyard Fountain', 'Tropical Garden', 'Heritage Architecture', 'Staff', 'Garage'],
    featured: true, rating: 4.95, reviews: 14, available: true,
    tags: ['Heritage', 'Pool', 'Goa'],
  },
  {
    id: '27',
    title: 'Navi Mumbai Waterfront Flat',
    description: 'Premium 3BHK apartment with uninterrupted creek and city views in Kharghar, Navi Mumbai. Modern tower with club facilities, walking distance to Kharghar station, and upcoming metro connectivity.',
    price: 55000,
    priceUnit: 'month',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    area: 1550,
    location: { address: 'Sector 12, Kharghar', city: 'Navi Mumbai', state: 'Maharashtra', zip: '410210', lat: 19.0478, lng: 73.0694 },
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    ],
    amenities: ['Creek View', 'Clubhouse', 'Pool', 'Gym', 'Near Station', 'CCTV'],
    featured: false, rating: 4.4, reviews: 95, available: true,
    tags: ['Waterfront', 'Navi Mumbai', 'Value'],
  },
  {
    id: '28',
    title: 'Malviya Nagar South Delhi Duplex',
    description: 'Premium duplex flat in South Delhi\'s beloved Malviya Nagar. Two-storey layout with a terrace, modular kitchen, and a quiet residential lane. Walking distance to Hauz Khas village for dining and nightlife.',
    price: 130000,
    priceUnit: 'month',
    type: 'Duplex',
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    location: { address: 'Malviya Nagar, South Delhi', city: 'New Delhi', state: 'Delhi', zip: '110017', lat: 28.5355, lng: 77.2100 },
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800',
    ],
    amenities: ['Terrace', 'Modular Kitchen', 'Duplex Layout', 'Parking', 'Near Metro', 'Gated Colony'],
    featured: false, rating: 4.6, reviews: 39, available: true,
    tags: ['South Delhi', 'Duplex', 'Terrace'],
  },
];

// GET all properties
router.get('/', (req, res) => {
  const { city, minPrice, maxPrice, bedrooms, type, search } = req.query;

  let filtered = [...properties];

  if (city) filtered = filtered.filter(p => p.location.city.toLowerCase().includes(city.toLowerCase()));
  if (minPrice) filtered = filtered.filter(p => p.price >= parseInt(minPrice));
  if (maxPrice) filtered = filtered.filter(p => p.price <= parseInt(maxPrice));
  if (bedrooms) filtered = filtered.filter(p => p.bedrooms >= parseInt(bedrooms));
  if (type) filtered = filtered.filter(p => p.type.toLowerCase() === type.toLowerCase());
  if (search) {
    const q = search.toLowerCase();
    filtered = filtered.filter(p =>
      p.title.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.location.city.toLowerCase().includes(q)
    );
  }

  res.json({ success: true, count: filtered.length, data: filtered });
});

// GET featured properties
router.get('/featured', (req, res) => {
  const featured = properties.filter(p => p.featured);
  res.json({ success: true, data: featured });
});

// GET property by ID
router.get('/:id', (req, res) => {
  const property = properties.find(p => p.id === req.params.id);
  if (!property) return res.status(404).json({ success: false, message: 'Property not found' });
  res.json({ success: true, data: property });
});

module.exports = router;
